{
 "title": "Temperature Simulator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Unit Wise Average Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unit A",
   "type": "gauge",
   "description": "Average Temperature of Unit A",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(temperature{unit=\"a\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unit B",
   "type": "gauge",
   "description": "Average Temperature of Unit B",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(temperature{unit=\"b\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unit C",
   "type": "gauge",
   "description": "Average Temperature of Unit C",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(temperature{unit=\"c\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heat Map Of All Sensors",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "temperature{job=\"test\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "All Sensors of Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Unit A Sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature{sensor=\"a1\"}",
     "legendFormat": "A1"
    },
    {
     "expr": "temperature{sensor=\"a2\"}",
     "legendFormat": "A2"
    },
    {
     "expr": "temperature{sensor=\"a3\"}",
     "legendFormat": "A3"
    }
   ]
  },
  {
   "title": "Unit B Sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature{sensor=\"b1\"}",
     "legendFormat": "B1"
    },
    {
     "expr": "temperature{sensor=\"b2\"}",
     "legendFormat": "B2"
    },
    {
     "expr": "temperature{sensor=\"b3\"}",
     "legendFormat": "B3"
    }
   ]
  },
  {
   "title": "Unit C Sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature{sensor=\"c1\"}",
     "legendFormat": "C1"
    },
    {
     "expr": "temperature{sensor=\"c2\"}",
     "legendFormat": "C2"
    },
    {
     "expr": "temperature{sensor=\"c3\"}",
     "legendFormat": "C3"
    }
   ]
  }
 ]
}